modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''E.D.I.T.H.-style tactical loadout and regear system.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21]"
ordering="NONE"
side="BOTH"
